export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      driver_profile: {
        Row: {
          uuid: string;
          first_name: string;
          last_name: string;
          email: string;
          phone_num: string;
          phone_verified: boolean;
          check1: boolean;
          check2: boolean;
          nin: string | null;
          admin_verify: boolean;
          profile_img: string | null;
          license_upload: string | null;
          is_online: boolean;
          location_lat: number | null;
          location_lng: number | null;
          experience: string | null;
          health_status: 'yes' | 'no';
          health_yes: string | null;
          address: string | null;
          city: string | null;
          state: string | null;
          push_notification: boolean;
          expo_push_token: string | null;
          push_token_updated_at: string | null;
          wallet_account: string | null;
          wallet_balance: number;
          bank_name: string | null;
          account_name: string | null;
          budpay_customer_code: string | null;
          transfer_pin: string | null;
          payout_bank_code: string | null;
          payout_bank_name: string | null;
          payout_account_number: string | null;
          payout_account_name: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          uuid: string;
          first_name: string;
          last_name: string;
          email: string;
          phone_num: string;
          phone_verified?: boolean;
          check1?: boolean;
          check2?: boolean;
          nin?: string | null;
          admin_verify?: boolean;
          profile_img?: string | null;
          license_upload?: string | null;
          is_online?: boolean;
          location_lat?: number | null;
          location_lng?: number | null;
          experience?: string | null;
          health_status?: 'yes' | 'no';
          health_yes?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          push_notification?: boolean;
          expo_push_token?: string | null;
          push_token_updated_at?: string | null;
          wallet_account?: string | null;
          wallet_balance?: number;
          bank_name?: string | null;
          account_name?: string | null;
          budpay_customer_code?: string | null;
          transfer_pin?: string | null;
          payout_bank_code?: string | null;
          payout_bank_name?: string | null;
          payout_account_number?: string | null;
          payout_account_name?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          uuid?: string;
          first_name?: string;
          last_name?: string;
          email?: string;
          phone_num?: string;
          phone_verified?: boolean;
          check1?: boolean;
          check2?: boolean;
          nin?: string | null;
          admin_verify?: boolean;
          profile_img?: string | null;
          license_upload?: string | null;
          is_online?: boolean;
          location_lat?: number | null;
          location_lng?: number | null;
          experience?: string | null;
          health_status?: 'yes' | 'no';
          health_yes?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          push_notification?: boolean;
          expo_push_token?: string | null;
          push_token_updated_at?: string | null;
          wallet_account?: string | null;
          wallet_balance?: number;
          bank_name?: string | null;
          account_name?: string | null;
          budpay_customer_code?: string | null;
          transfer_pin?: string | null;
          payout_bank_code?: string | null;
          payout_bank_name?: string | null;
          payout_account_number?: string | null;
          payout_account_name?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'driver_profile_uuid_fkey';
            columns: ['uuid'];
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      driver_transaction: {
        Row: {
          id: string;
          driver_uuid: string;
          reference: string;
          type: string;
          status: string;
          channel: string | null;
          gateway: string | null;
          currency: string;
          amount: number;
          fee: number;
          requested_amount: number | null;
          sender_name: string | null;
          sender_account: string | null;
          bank_code: string | null;
          bank_name: string | null;
          account_number: string | null;
          account_name: string | null;
          narration: string | null;
          paid_at: string | null;
          raw_payload: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          driver_uuid: string;
          reference: string;
          type: string;
          status?: string;
          channel?: string | null;
          gateway?: string | null;
          currency?: string;
          amount: number;
          fee?: number;
          requested_amount?: number | null;
          sender_name?: string | null;
          sender_account?: string | null;
          bank_code?: string | null;
          bank_name?: string | null;
          account_number?: string | null;
          account_name?: string | null;
          narration?: string | null;
          paid_at?: string | null;
          raw_payload?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          driver_uuid?: string;
          reference?: string;
          type?: string;
          status?: string;
          channel?: string | null;
          gateway?: string | null;
          currency?: string;
          amount?: number;
          fee?: number;
          requested_amount?: number | null;
          sender_name?: string | null;
          sender_account?: string | null;
          bank_code?: string | null;
          bank_name?: string | null;
          account_number?: string | null;
          account_name?: string | null;
          narration?: string | null;
          paid_at?: string | null;
          raw_payload?: Json | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'driver_transaction_driver_uuid_fkey';
            columns: ['driver_uuid'];
            referencedRelation: 'driver_profile';
            referencedColumns: ['uuid'];
          },
        ];
      };
      rider_profile: {
        Row: {
          uuid: string;
          first_name: string;
          last_name: string;
          phone_num: string;
        };
        Insert: {
          uuid: string;
          first_name: string;
          last_name: string;
          phone_num: string;
        };
        Update: {
          uuid?: string;
          first_name?: string;
          last_name?: string;
          phone_num?: string;
        };
        Relationships: [];
      };
      rider_booking: {
        Row: {
          id: string;
          rider_id: string;
          assigned_driver: string | null;
          pricing_id: string | null;
          pick_up: string;
          pickup_lat: number;
          pickup_lng: number;
          drop_off: string;
          drop_lat: number;
          drop_lng: number;
          add_stop: string | null;
          addstop_lat: number | null;
          addstop_lng: number | null;
          amount: number;
          guest_rider: boolean;
          guest_rider_name: string | null;
          guest_rider_number: string | null;
          total_km: number | null;
          total_time: number | null;
          base_fare: number;
          distance_fare: number;
          time_fare: number;
          delay_fare: number;
          vat_amount: number;
          state_levy: number;
          total_fare: number;
          payment_method: 'wallet' | 'transfer' | 'cash' | 'card';
          payment_status: 'unpaid' | 'paid';
          vehicle_type: 'Limpopo Pro' | 'Limpopo Promax' | 'Limpopo Comfort';
          driver_arrived_at: string | null;
          trip_started_at: string | null;
          trip_completed_at: string | null;
          ride_status: 'open' | 'accepted' | 'arrived' | 'in_progress' | 'completed' | 'cancelled' | 'expired';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          rider_id: string;
          assigned_driver?: string | null;
          pricing_id?: string | null;
          pick_up: string;
          pickup_lat: number;
          pickup_lng: number;
          drop_off: string;
          drop_lat: number;
          drop_lng: number;
          add_stop?: string | null;
          addstop_lat?: number | null;
          addstop_lng?: number | null;
          amount?: number;
          guest_rider?: boolean;
          guest_rider_name?: string | null;
          guest_rider_number?: string | null;
          total_km?: number | null;
          total_time?: number | null;
          base_fare?: number;
          distance_fare?: number;
          time_fare?: number;
          delay_fare?: number;
          vat_amount?: number;
          state_levy?: number;
          total_fare?: number;
          payment_method: 'wallet' | 'transfer' | 'cash' | 'card';
          payment_status?: 'unpaid' | 'paid';
          vehicle_type: 'Limpopo Pro' | 'Limpopo Promax' | 'Limpopo Comfort';
          driver_arrived_at?: string | null;
          trip_started_at?: string | null;
          trip_completed_at?: string | null;
          ride_status?: 'open' | 'accepted' | 'arrived' | 'in_progress' | 'completed' | 'cancelled' | 'expired';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          rider_id?: string;
          assigned_driver?: string | null;
          pricing_id?: string | null;
          pick_up?: string;
          pickup_lat?: number;
          pickup_lng?: number;
          drop_off?: string;
          drop_lat?: number;
          drop_lng?: number;
          add_stop?: string | null;
          addstop_lat?: number | null;
          addstop_lng?: number | null;
          amount?: number;
          guest_rider?: boolean;
          guest_rider_name?: string | null;
          guest_rider_number?: string | null;
          total_km?: number | null;
          total_time?: number | null;
          base_fare?: number;
          distance_fare?: number;
          time_fare?: number;
          delay_fare?: number;
          vat_amount?: number;
          state_levy?: number;
          total_fare?: number;
          payment_method?: 'wallet' | 'transfer' | 'cash' | 'card';
          payment_status?: 'unpaid' | 'paid';
          vehicle_type?: 'Limpopo Pro' | 'Limpopo Promax' | 'Limpopo Comfort';
          driver_arrived_at?: string | null;
          trip_started_at?: string | null;
          trip_completed_at?: string | null;
          ride_status?: 'open' | 'accepted' | 'arrived' | 'in_progress' | 'completed' | 'cancelled' | 'expired';
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'rider_booking_rider_id_fkey';
            columns: ['rider_id'];
            referencedRelation: 'rider_profile';
            referencedColumns: ['uuid'];
          },
        ];
      };
      schedule_booking: {
        Row: {
          id: string;
          rider_id: string;
          schedule_type: 'ride' | 'hourly' | 'hire';
          schedule_date: string;
          pickup_time: string;
          passenger_num: number;
          pick_up: string;
          pickup_lat: number | null;
          pickup_lng: number | null;
          drop_off: string | null;
          drop_lat: number | null;
          drop_lng: number | null;
          add_stop: string | null;
          addstop_lat: number | null;
          addstop_lng: number | null;
          guest_rider: boolean;
          guest_rider_name: string | null;
          guest_rider_number: string | null;
          pricing_id: string | null;
          vehicle_type: 'Limpopo Pro' | 'Limpopo Promax' | 'Limpopo Comfort' | null;
          base_fare: number;
          distance_fare: number;
          time_fare: number;
          delay_fare: number;
          amount: number;
          vat_amount: number;
          state_levy: number;
          total_fare: number;
          payment_method: 'wallet' | 'transfer' | 'cash' | 'card' | null;
          assigned_driver: string | null;
          booking_status: 'pending' | 'confirmed' | 'cancelled' | 'expired' | 'converted';
          converted_rider_booking_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          rider_id: string;
          schedule_type?: 'ride' | 'hourly' | 'hire';
          schedule_date: string;
          pickup_time: string;
          passenger_num?: number;
          pick_up: string;
          pickup_lat?: number | null;
          pickup_lng?: number | null;
          drop_off?: string | null;
          drop_lat?: number | null;
          drop_lng?: number | null;
          add_stop?: string | null;
          addstop_lat?: number | null;
          addstop_lng?: number | null;
          guest_rider?: boolean;
          guest_rider_name?: string | null;
          guest_rider_number?: string | null;
          pricing_id?: string | null;
          vehicle_type?: 'Limpopo Pro' | 'Limpopo Promax' | 'Limpopo Comfort' | null;
          base_fare?: number;
          distance_fare?: number;
          time_fare?: number;
          delay_fare?: number;
          amount?: number;
          vat_amount?: number;
          state_levy?: number;
          total_fare?: number;
          payment_method?: 'wallet' | 'transfer' | 'cash' | 'card' | null;
          assigned_driver?: string | null;
          booking_status?: 'pending' | 'confirmed' | 'cancelled' | 'expired' | 'converted';
          converted_rider_booking_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          rider_id?: string;
          schedule_type?: 'ride' | 'hourly' | 'hire';
          schedule_date?: string;
          pickup_time?: string;
          passenger_num?: number;
          pick_up?: string;
          pickup_lat?: number | null;
          pickup_lng?: number | null;
          drop_off?: string | null;
          drop_lat?: number | null;
          drop_lng?: number | null;
          add_stop?: string | null;
          addstop_lat?: number | null;
          addstop_lng?: number | null;
          guest_rider?: boolean;
          guest_rider_name?: string | null;
          guest_rider_number?: string | null;
          pricing_id?: string | null;
          vehicle_type?: 'Limpopo Pro' | 'Limpopo Promax' | 'Limpopo Comfort' | null;
          base_fare?: number;
          distance_fare?: number;
          time_fare?: number;
          delay_fare?: number;
          amount?: number;
          vat_amount?: number;
          state_levy?: number;
          total_fare?: number;
          payment_method?: 'wallet' | 'transfer' | 'cash' | 'card' | null;
          assigned_driver?: string | null;
          booking_status?: 'pending' | 'confirmed' | 'cancelled' | 'expired' | 'converted';
          converted_rider_booking_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'schedule_booking_rider_id_fkey';
            columns: ['rider_id'];
            referencedRelation: 'rider_profile';
            referencedColumns: ['uuid'];
          },
          {
            foreignKeyName: 'schedule_booking_converted_rider_booking_id_fkey';
            columns: ['converted_rider_booking_id'];
            referencedRelation: 'rider_booking';
            referencedColumns: ['id'];
          },
        ];
      };
    };
    Views: Record<string, never>;
    Functions: {
      driver_has_transfer_pin: {
        Args: Record<string, never>;
        Returns: boolean;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
